-- Withings公式APIスペックに基づく全ワークアウトカテゴリのシードデータ
INSERT INTO withings_workout_categories (
  category_id, category_key, label_ja, label_en, created_at, updated_at
)
VALUES
  (1, 'walking_running', 'ウォーキング', 'Walk', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (2, 'run', 'ランニング', 'Run', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (3, 'hiking', 'ハイキング', 'Hiking', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (4, 'skating', 'スケート', 'Skating', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (5, 'bmx', 'BMX', 'BMX', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (6, 'cycling', 'サイクリング', 'Bicycling', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (7, 'swimming', '水泳', 'Swimming', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (8, 'surfing', 'サーフィン', 'Surfing', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (9, 'kitesurfing', 'カイトサーフィン', 'Kitesurfing', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (10, 'windsurfing', 'ウィンドサーフィン', 'Windsurfing', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (11, 'bodyboard', 'ボディボード', 'Bodyboard', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (12, 'tennis', 'テニス', 'Tennis', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (13, 'table_tennis', '卓球', 'Table tennis', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (14, 'squash', 'スカッシュ', 'Squash', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (15, 'badminton', 'バドミントン', 'Badminton', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (16, 'lift_weights', 'ウェイトを持ち上げる', 'Lift weights', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (17, 'fitness', 'フィットネス', 'Fitness', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (18, 'elliptical', '楕円形', 'Elliptical', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (19, 'pilates', 'ピラティス', 'Pilates', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (20, 'basket_ball', 'バスケットボール', 'Basket-ball', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (21, 'soccer', 'サッカー', 'Soccer', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (22, 'football', 'フットボール', 'Football', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (23, 'rugby', 'ラグビー', 'Rugby', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (24, 'volley_ball', 'バレーボール', 'Volley-ball', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (25, 'waterpolo', '水球', 'Waterpolo', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (26, 'horse_riding', '乗馬', 'Horse riding', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (27, 'golf', 'ゴルフ', 'Golf', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (28, 'yoga', 'ヨガ', 'Yoga', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (29, 'dancing', 'ダンシング', 'Dancing', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (30, 'boxing', 'ボクシング', 'Boxing', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (31, 'fencing', 'フェンシング', 'Fencing', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (32, 'wrestling', 'レスリング', 'Wrestling', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (33, 'martial_arts', '武道', 'Martial arts', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (34, 'skiing', 'スキー', 'Skiing', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (35, 'snowboarding', 'スノーボード', 'Snowboarding', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (36, 'other', 'その他', 'Other', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (128, 'no_activity', '活動なし', 'No activity', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (187, 'rowing', 'ボート漕ぎ', 'Rowing', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (188, 'zumba', 'ズンバ', 'Zumba', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (191, 'baseball', '野球', 'Baseball', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (192, 'handball', 'ハンドボール', 'Handball', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (193, 'hockey', 'ホッケー', 'Hockey', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (194, 'ice_hockey', 'アイスホッケー', 'Ice hockey', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (195, 'climbing', 'クライミング', 'Climbing', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (196, 'ice_skating', 'アイススケート', 'Ice skating', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (272, 'multi_sport', 'マルチスポーツ', 'Multi-sport', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (306, 'indoor_walk', '屋内散歩', 'Indoor walk', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (307, 'indoor_running', '室内ランニング', 'Indoor running', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (308, 'indoor_cycling', 'インドアサイクリング', 'Indoor cycling', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (309, 'breathing_excercise', '呼吸法', 'Breathing excercise', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (455, 'standup_paddleboarding', 'スタンドアップパドルボーディング', 'Standup Paddleboarding', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (456, 'padel', 'パデル', 'Padel', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (457, 'gaming', 'ゲーム', 'Gaming', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (490, 'beach_volleyball', 'ビーチバレーボール', 'Beach volleyball', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (491, 'stair_stepper', 'ステアステッパー', 'Stair Stepper', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (492, 'skateboarding', 'スケートボード', 'Skateboarding', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (493, 'parkour', 'パルクール', 'Parkour', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (494, 'kayaking', 'カヤック', 'Kayaking', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (495, 'canoeing', 'カヌー', 'Canoeing', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (496, 'sailing', 'セーリング', 'Sailing', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (497, 'fishing', '釣り', 'Fishing', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (498, 'trail_running', 'トレイルランニング', 'Trail Running', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (499, 'snowshoeing', 'スノーシューイング', 'Snowshoeing', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (500, 'paintball', 'ペイントボール', 'Paintball', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (501, 'archery', 'アーチェリー', 'Archery', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (502, 'scuba_diving', 'スキューバダイビング', 'Scuba Diving', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (503, 'baseball_training', '野球のトレーニング', 'Baseball Training', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (504, 'biathlon', 'バイアスロン', 'Biathlon', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (505, 'bocce', 'ボッチェ', 'Bocce', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (506, 'petanque', 'ペタンク', 'Pétanque', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (507, 'paragliding', 'パラグライダー', 'Paragliding', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (508, 'frisbee', 'フリスビー', 'Frisbee', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (509, 'skydiving', 'スカイダイビング', 'Skydiving', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (510, 'pickleball', 'ピックルボール', 'Pickleball', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (511, 'cornhole', 'コーンホール', 'Cornhole', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (512, 'dodgeball', 'ドッジボール', 'Dodgeball', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (513, 'ultimate', '究極の', 'Ultimate', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (514, 'teqball', 'テックボール', 'Teqball', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (515, 'pushing_a_wheelchair_running_pace', '車椅子を押す（走るペース）', 'Pushing a Wheelchair (Running Pace)', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (516, 'pushing_a_wheelchair_walking_pace', '車椅子を押す（歩くペース）', 'Pushing a Wheelchair (Walking Pace)', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (517, 'athletics', '陸上競技', 'Athletics', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (518, 'track_cycling', 'トラックサイクリング', 'Track Cycling', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (519, 'pentathlon', '五種競技', 'Pentathlon', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (520, 'sport_shooting', 'スポーツ射撃', 'Sport Shooting', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (521, 'triathlon', 'トライアスロン', 'Triathlon', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (522, 'diving', 'ダイビング', 'Diving', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (523, 'mountain_biking', 'マウンテンバイク', 'Mountain Biking', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (524, 'gravel_biking', 'グラベルバイク', 'Gravel Biking', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (525, 'e_biking', '電動自転車', 'E-Biking', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (526, 'e_mountain_biking', 'Eマウンテンバイク', 'E-Mountain Biking', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (527, 'handcycling', 'ハンドサイクリング', 'Handcycling', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (528, 'velomobile', 'ベロモービル', 'Velomobile', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (529, 'backcountry_skiing', 'バックカントリースキー', 'Backcountry Skiing', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (530, 'nordic_skiing', 'ノルディックスキー', 'Nordic Skiing', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (531, 'roller_skiing', 'ローラースキー', 'Roller Skiing', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (532, 'racquetball', 'ラケットボール', 'Racquetball', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (534, 'hip_hop', 'ヒップホップ', 'Hip Hop', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (535, 'muaythai', 'ムエタイ', 'Muaythai', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (536, 'taekwondo', 'テコンドー', 'Taekwondo', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (537, 'judo', '柔道', 'Judo', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (538, 'trampoline', 'トランポリン', 'Trampoline', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (539, 'standing_frame', 'スタンディングフレーム', 'Standing Frame', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (540, 'seated_strenght', '座位の強さ', 'Seated Strenght', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (541, 'seated_cardio', '座って有酸素運動', 'Seated Cardio', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (542, 'walk_with_walker', 'ウォーカーと一緒に歩く', 'Walk With Walker', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (543, 'walk_with_cane', '杖をついて歩く', 'Walk With Cane', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (544, 'breaking', 'ブレーキング', 'Breaking', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (545, 'chores', '家事', 'Chores', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (546, 'crossfit', 'クロスフィット', 'Crossfit', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (547, 'spinclass', 'スピンクラス', 'Spinclass', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (548, 'cricket', 'クリケット', 'Cricket', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (549, 'flamenco_dancing', 'フラメンコダンス', 'Flamenco Dancing', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (550, 'hiit', 'HIIT', 'HIIT', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (551, 'meditation', '瞑想', 'Meditation', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (552, 'stretching', 'ストレッチ', 'Stretching', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (553, 'yard_work_gardening', '庭仕事 ガーデニング', 'Yard Work Gardening', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (554, 'cleaning', 'クリーニング', 'Cleaning', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (555, 'public_speaking', '人前で話す', 'Public Speaking', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (556, 'spikeball', 'スパイクボール', 'Spikeball', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (557, 'lacrosse', 'ラクロス', 'Lacrosse', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (558, 'baby_wearing', 'ベビーウェアリング', 'Baby Wearing', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (559, 'dog_walking', '犬の散歩', 'Dog Walking', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (560, 'breathing_excercises', '呼吸法', 'Breathing excercises', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (561, 'balance_drills', 'バランスドリル', 'Balance Drills', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (562, 'pushing_a_stroller', 'ベビーカーを押す', 'Pushing a Stroller', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (563, 'toddler_wearing', '幼児の着用', 'Toddler Wearing', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (564, 'bowling', 'ボーリング', 'Bowling', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (565, 'lasertag', 'レーザータグ', 'Lasertag', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (566, 'nordic_walking', 'ノルディックウォーキング', 'Nordic Walking', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (567, 'sumo_wrestling', '大相撲', 'Sumo Wrestling', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER)),
  (568, 'cooking', '料理', 'Cooking', CAST(strftime('%s', 'now') AS INTEGER), CAST(strftime('%s', 'now') AS INTEGER))
ON CONFLICT(category_id) DO UPDATE SET
  category_key = excluded.category_key,
  label_ja = excluded.label_ja,
  label_en = excluded.label_en,
  updated_at = excluded.updated_at;
